// flow-typed signature: c15ee40f742c6dd3fc72e97b38a46ddc
// flow-typed version: <<STUB>>/babel-plugin-react-native-classname-to-style_v^1.2.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-native-classname-to-style'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-native-classname-to-style' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-react-native-classname-to-style/index' {
  declare module.exports: $Exports<'babel-plugin-react-native-classname-to-style'>;
}
declare module 'babel-plugin-react-native-classname-to-style/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-native-classname-to-style'>;
}
