// flow-typed signature: fac0d0ee397f37fd3e9aa3ccf243e5c5
// flow-typed version: <<STUB>>/babel-plugin-react-native-platform-specific-extensions_v^1.1.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-native-platform-specific-extensions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-native-platform-specific-extensions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-react-native-platform-specific-extensions/index' {
  declare module.exports: $Exports<'babel-plugin-react-native-platform-specific-extensions'>;
}
declare module 'babel-plugin-react-native-platform-specific-extensions/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-native-platform-specific-extensions'>;
}
