// flow-typed signature: dc95c5db7cd21e42e94da7f2ce0b1ddb
// flow-typed version: <<STUB>>/react-native-stylus-transformer_v^1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-stylus-transformer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-stylus-transformer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-stylus-transformer/index' {
  declare module.exports: $Exports<'react-native-stylus-transformer'>;
}
declare module 'react-native-stylus-transformer/index.js' {
  declare module.exports: $Exports<'react-native-stylus-transformer'>;
}
